xcodeproj 'LyricsWikia Tests'
workspace '../LyricsWikia'
inhibit_all_warnings!

def import_pods
  pod 'LyricsWikia', :path => '../'
  pod 'SenTestingKitAsync', '~> 1.0'
end

target :ios do
  platform :ios, '5.0'
  link_with 'iOS Tests'
  import_pods
end

target :osx do
  platform :osx, '10.7'
  link_with 'OSX Tests'
  import_pods
end